project:
  type: website
  output-dir: docs

website:
  title: "Data Science for Transport Planning"
  repo-url: "https://github.com/tdscience/tartu26"
  repo-actions: [issue]
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Materials by [Robin Lovelace](https://www.robinlovelace.net/), 2026."
  sidebar:
    background: primary
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/tdscience/tartu26
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: workbook.qmd
        text: Workbook
      - href: prerequisites.qmd
        text: Prerequisites
      - href: https://tdscience.github.io/dstp/
        text: Full Course Materials

format:
  html:
    theme: lux
    toc: true
    title-prefix: "Tartu 2026 - "
    number-sections: true
    author-meta: "Robin Lovelace & contributors"
    date-meta: "2026"
    copyright: "© 2026 Robin Lovelace"
    license: "CC BY-SA"

execute:
  freeze: false
  cache: true
  message: false
  warning: false

bibliography: references.bib
