name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/itsleeds/tds:latest
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
